version: "3.8"
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - 1433:1433
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_PID=Standard
      - SA_PASSWORD=Echo1234
      - MSSQL_AGENT_ENABLED=true
#     volumes:
#       - ./dqm-data/sqlserver:/var/opt/mssql/backup
#       - sqlserver_data:/var/opt/mssql

# volumes:
#   elastic_data:
#     driver: local
#   sqlserver_data:
#     driver: local