apiVersion: ENC[AES256_GCM,data:tAk=,iv:+SMdDi24u1kWKsHGx7G2GO7CncFvOpTSrU7y/Lzjchg=,tag:Swmvmyp5qhaz/P+DLkLcfA==,type:str]
kind: ENC[AES256_GCM,data:Kx5CVVdD,iv:9m60Yi3RS9hFjXbKWMhXLSZZTchwLIoY/vwqJ7ori9o=,tag:ESOWFKTTtTtByXXRkCjcgw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:HQiWemn3lOxEWeMGPZuc4rUhODDUgg==,iv:8EJ2NJ2R5tGKwbyNDhlK9x5ItRK/xhNiD/yOcKpCnN0=,tag:IX8jXtzfGPpSIplIfKCuuw==,type:str]
    namespace: ENC[AES256_GCM,data:vTt6EwUHDQ==,iv:CxPaBPsSVUgvkWkP638ZG748ZcKntQnlshJgmrmzMG8=,tag:WmfpRohjBgIbgZo6az0WQg==,type:str]
    labels:
        team: ENC[AES256_GCM,data:kwo5Bn32biA=,iv:WKSVH9Uab2n9dGvg1EvpU+Nc665e096vGhBNcB9WK4c=,tag:yuYEizf/aDwJPolrqhkxMA==,type:str]
        app: ENC[AES256_GCM,data:wzsWH/5prLbzYy8=,iv:fGLt7wxJfMaRCRRVw1RoONYCENpwTzw4YLIoksH42zY=,tag:BMD6clUlDSwhrhJUJQz9ag==,type:str]
stringData:
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:sPnY1QD33/0cfaoQrUi5WMgTOzQZ4+Z3Qn7AmjS+Pg/BE3zoPCAM3w==,iv:SQ6ArDJgqta2/bLDTiTyk631L/pae3X9/e/w3DvXy5M=,tag:y8cLP0bGsnGQ4l6MFT8V1A==,type:str]
    SQL_PASSWORD: ENC[AES256_GCM,data:8BBwS1JPTSM+F9A5,iv:1ujKZMmXiGStggwhK47GxKtO50c2DULkZeb2Xfwe4PQ=,tag:Qex4e/mACSV0/5FSHOsGqA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-06-15T17:28:18Z"
    mac: ENC[AES256_GCM,data:/DRdV9vTC6eiSvye/+bwraknCYQW30AeoCd9O+Fz/LlbJMzHvxBFTdazBn0yb96k2+k1dZtlNZYH3/ThKJb+zLxih9Ljwr8L0SsJELaPyFewNfZ8IV1Non4ptGcQFfp6rCWWJWAkUe5+ftTbnoXgKyWWU6VMmW5lHS792Q82Eu8=,iv:koFuf6VPi7T+hqpbK1Sjraf+8qjQiabIR+10fm17pDU=,tag:qlhad1iiDXe33TC5ExnbQQ==,type:str]
    pgp:
        - created_at: "2021-06-15T17:28:18Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAxlemAQVmlKUAQ/9GiVdXl4TzTJsiBod6hc9zdM7O2wIevFw+4x14na5jWLk
            zzLpjyv8ohfaI+pK9gFqJ2lryV7mAFjPF5w6Q9kPunmVDfi25zLej3ccM46vhkSB
            /9EHnOy4ZpTqWGfvByg5Kvwj/1TvJxBFfUG+MqXGgWsc5ak4FQc1vY5jrC/ZL04r
            ptcV4U3XYqIhG+S1V/hBK+jBi8SeNnNLVApcPQTmJw/BoEyTV8sdQ6TMafq1cqFp
            ZftSi67M7mSPgb09X133x6LqTtju60jBYIC3oy5K60QpRlnXGRa5BvTr2ni2SSFB
            EOul3gz6HtC4HtG2aIKuW/HgHES31fyJW8A+nWC0+jnHbI0eJ+lyumPGnVaq6w+8
            v99kRY6+hjt9tZpd8D7EHd8pU2rF3+Y1ncJ2sCd9A1RKWpf7B2GQtbkJqFNR2FsN
            VyylJq9RSY08DWTu9uAwEP54LaAn/mL1ZKadKYI08KhomqJQQG3uwFUsslmCJRaI
            WraYDaIhX8XuSQ/lLtCoKuwsekfs4FtzhIron1rlS1jUBgsGdty+xVneck1Z1RqX
            K54u3MpA0w5VpmIKOwtmSAGPswO9FwoWGartnzc50Wn0DWyW4+vPQtR29L+h7NLm
            t1nTkse1Im3krmL9iM4h0FTp9HPIgZgS47gW45/pydhuogzvNX3pi7TVQrRIOwjS
            XgFu6xoe0OvBVy8lkPeWwd9Ux0jlRu7cmTcurSUeuYG9LsnD4W+qNGgwsqfqcNll
            0MVpShEtL7LxJdoqDeTzgYGTcCk/C1NPbnyt+JRd+z5qKAsXAc2pXg4/RKT0RAU=
            =wfHW
            -----END PGP MESSAGE-----
          fp: 8ED5334517F886CC37EA1A7F7F6F8C17B3621F18
    unencrypted_suffix: _unencrypted
    version: 3.7.1
