---
apiVersion: v1
kind: ConfigMap
metadata:
  name: checkrunner-api-config
  namespace: default
  labels:
    team: datateam
    app: checkrunner
data:
    YAML_MANAGER_TYPE: s3
    S3_BUCKET: echo-bi-datateam-dev
    S3_FOLDER: checkrunner
    AWS_ACCESS_KEY: AKIA5BPDHQI65MKEB746
    AWS_ROLE_ARN: arn:aws:iam::896514097725:role/echo-sec-dev-bi-datateam-checkrunner-role
    AWS_EXTERNAL_ID: 896514097725
    LOG_LEVEL: 30
    SQL_DRIVER: ODBC Driver 17 for SQL Server
    ODS_SERVER: cdcdevlodsdb01.dev.echogl.net
    DB01_SERVER:
    SQL_USER: checkrunner
    ODS_VAULT: ODSVault
    ODS_MART_TRACKING: ODSMartTracking
    ODS_MART_Sourcing: ODSMartSourcing
    ODS_MART_TL_QUOTING: ODSMartTLQuoting
    ODS_Log: ODSLog
    ECHO_OPTIMIZER: EchoOptimizer
    ODS_INTEGRATION: ODSIntegration